title: DOTP
description: Dump Of The Probing
author: Nate
avatar: /assets/images/selfie1.png
email: whtnek@gmail.com

plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate

paginate: 6

# Google Analytics tracking ID
google_analytics: G-7GT5Q9K67G 

# Uncomment the below lines and set the Disqus shortname for enabling Disqus
# 
# disqus:

# Jekyll
# ======
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec

skin: daylight
# Jekyll SEO Tag (Optional)
# =========================
twitter:
  username: ngzhio
  card: summary
logo: /images/selfie2.jpg
social:
  name: Jisu Chung
  links:
    - https://twitter.com/ngzhio
    - https://www.facebook.com/ngzhio
    - https://github.com/jayChung0302
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: ko
